### ISSUE TITLE
Make total project coverage configurable

### ISSUE THREAD

**Issue by lukasz-kalnik-gcx** [mi-kas/kover-report#105]
Seems like the "total project coverage" currently shows the class coverage.
It would be nice if it could be configured e.g. to show branch coverage.

**Comment by mi-kas** [comment]
Thanks for bringing this up 👍 Currently we use the line coverage for showing the total project coverage (see code [here](https://github.com/mi-kas/kover-report/blob/main/src/reader.ts#L20)). But it would definetly make sense to make this configurable

**Comment by lukasz-kalnik-gcx** [comment]
Thanks for the quick answer!

**Comment by mi-kas** [comment]
Configure option for this was released just now with release [v1.5](https://github.com/mi-kas/kover-report/releases/tag/v1.5) but also made available for the major version `v1`.

**Comment by lukasz-kalnik-gcx** [comment]
Thank you once more for the super quick reaction!
