### ISSUE TITLE
Unable to publish Kover code coverage report as a comment in pull requests

### ISSUE THREAD

**Issue by xxfast** [mi-kas/kover-report#111]
Running into this issue and wondering if any recent changes has caused this. 

My action is available [here](https://github.com/xxfast/KStore/actions/runs/4178572426/jobs/7237638956#step:7:1)

```
HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/mi-kas/kover-report/v1/webpack:/kover-report/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by mi-kas** [comment]
Hi @xxfast! Thanks for bringing this issue up. I think this is related to some missing permissions for the action in your repo. Could you try to add the "pull-request: write" permission to your `check` job and let me know if this solves the issue?

```
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
```

**Comment by xxfast** [comment]
Yup, that worked 🙌 

I wonder if this is a recent change. This could also be because I recently added [permissions to the top level](https://github.com/xxfast/KStore/commit/14124c4da0661e4883018bd1c6fdf7995d229b05). 

Either way - this is now solved!
