### ISSUE TITLE
HttpError: Not Found

### ISSUE THREAD

**Issue by matejuh** [mi-kas/kover-report#148]
Hello,
I would like to set up this Github action for my repository, but I get an error:
```
Run mi-kas/kover-report@v1.5
Event is push
HttpError: Not Found
    at /runner/_work/_actions/mi-kas/kover-report/v1.5/webpack:/kover-report/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Obviously it's not possible to `getChangedFiles` and I am wondering what can be the cause or how to debug it? I think token should have required permissions. The PR contains only version change for kover-report from v1 to v1.5.

**Comment by mi-kas** [comment]
Hi @matejuh! I think your issue is related to some missing permissions for the action in your repo. Could you try to apply this suggestion here: https://github.com/mi-kas/kover-report/issues/111#issuecomment-1431146784

Let me know if this solves you issue

**Comment by matejuh** [comment]
The problem was that pipeline was trigger by `push` action but `pull_request` is needed to have PR context.
