### ISSUE TITLE
Add type to actions

### ISSUE THREAD

**Issue by LeoColman** [mi-kas/kover-report#16]
Github Actions YAML usually isn't as useful as it could be.

[krzema12/github-actions-typing](https://github.com/krzema12/github-actions-typing)

This project setup a way to define types for github actions inputs to build a type-safe Kotlin DSL.

**Comment by LeoColman** [comment]
If you agree I can make a PR supporting this :)

**Comment by mi-kas** [comment]
I like that idea 👍 Feel free to open a PR for it
