### ISSUE TITLE
Exclusions not working

### ISSUE THREAD

**Issue by demonar** [mi-kas/kover-report#235]
I have a project that has kover 0.7.3 setup using exclusions. I'm getting different values on the kover report that I run manually vs the results on CI, and I detected that the exclusions are not accounted on the CI run

**Comment by mi-kas** [comment]
Sorry for the late reply, the action just reads the output of the kover report file and posts it's content to the PR. How are you triggering the report creation in your PR? Maybe you need to fix the exclusions there...
