### ISSUE TITLE
Distribution not supplied

### ISSUE THREAD

**Issue by qrutyy** [mi-kas/kover-report#270]
Im new to code coverage, so at first i am hust using the example workflow and getting build error: "Input required and not supplied: distribution". 
<img width="669" alt="image" src="https://github.com/mi-kas/kover-report/assets/64466788/2d50d66b-c195-4282-a962-22a8602bd343">

What can i do, to solve this issue?

**Comment by mi-kas** [comment]
Sorry for the late reply. I just updated the example setup in the readme to fix this problem. Please check it again here: https://github.com/mi-kas/kover-report/blob/main/README.md#example-workflow
