### ISSUE TITLE
Please release with action typings

### ISSUE THREAD

**Issue by krzema12** [mi-kas/kover-report#34]
Some time ago this commit was merged: https://github.com/mi-kas/kover-report/commit/f795c03040d47f60688b09d8cd88cfcf007cfa49
It would be cool to have it released, so that it's available under `v1` tag :smile: Could you please prepare a release?

**Comment by mi-kas** [comment]
Sure, I will release it soon. But I have a couple of features on its way I would like to finish first before a next release (will be v2 probably)

**Comment by mi-kas** [comment]
Closed by release [v1.1](https://github.com/mi-kas/kover-report/releases/tag/v1.1)

**Comment by krzema12** [comment]
@mi-kas thanks! Could you also update `v1` tag? It still points to some older version, and our logic relies on major version tags if they're available.

**Comment by mi-kas** [comment]
@krzema12 I'd like to go with a strict semantic versioning and therfore create always new versions for new functionalities with some backwards compability. Therefore the new action typings will be only available with `v1.1`.

**Comment by krzema12** [comment]
I understand and agree, but v1 isn't equal to v1.0 in GitHub's best practices :smile:
For more context please see:
* https://github.com/actions/toolkit/blob/main/docs/action-versioning.md#recommendations
* a ticket to another action owner where we explain the problem: https://github.com/gautamkrishnar/blog-post-workflow/issues/147

**Comment by mi-kas** [comment]
@krzema12 Ah ok, now I got what you mean. I just updated the v1 tag with the most recent changes. Thanks for the suggestion 👍

**Comment by krzema12** [comment]
Cool, thanks!

**Comment by krzema12** [comment]
@mi-kas FYI: https://github.com/krzema12/github-workflows-kt/pull/516
