### ISSUE TITLE
Error in reader.js

### ISSUE THREAD

**Issue by humblehacker** [mi-kas/kover-report#56]
My automated build just started failing, and I'm at a loss as to what to do with this error:
```
Run mi-kas/kover-report@v1.1
with:
path: /home/runner/work/<repo>/<repo>/build/jacoco/jacoco_shared_result.xml
token: ***
title: Code Coverage
update-comment: true
env:
JAVA_HOME: /opt/hostedtoolcache/Java_Corretto_jdk/11.0.17.8.1/x64
JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Corretto_jdk/11.0.17.8.1/x64
Event is pull_request

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

/home/runner/work/_actions/mi-kas/kover-report/v1.1/webpack:/kover-report/lib/reader.js:45
const lineCounter = (_a = counters.find(counter => counter['$'].type === 'LINE')) === null || _a === void 0 ? void 0 : _a['$'];
^
TypeError: Cannot read properties of undefined (reading 'find')
at getCoverageFromCounters (/home/runner/work/_actions/mi-kas/kover-report/v1.1/webpack:/kover-report/lib/reader.js:45:1)
at /home/runner/work/_actions/mi-kas/kover-report/v1.1/webpack:/kover-report/lib/reader.js:75:1
at Array.map (<anonymous>)
at /home/runner/work/_actions/mi-kas/kover-report/v1.1/webpack:/kover-report/lib/reader.js:68:1
at Array.reduce (<anonymous>)
at getFileCoverage (/home/runner/work/_actions/mi-kas/kover-report/v1.1/webpack:/kover-report/lib/reader.js:66:1)
at /home/runner/work/_actions/mi-kas/kover-report/v1.1/webpack:/kover-report/lib/action.js:47:1
at Generator.next (<anonymous>)
at fulfilled (/home/runner/work/_actions/mi-kas/kover-report/v1.1/webpack:/kover-report/lib/action.js:5:1)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by humblehacker** [comment]
I was able to work around it by reverting to v1.

**Comment by mi-kas** [comment]
@humblehacker Thanks for creating the issue! Could you mabe post your kover `report.xml` file here? Because it might be an issue related to parsing and reading that file as far I can see from your logs.

**Comment by humblehacker** [comment]
Thanks for your reply 😄 I'd rather not publicly post the coverage report. I thought maybe I could uncover the issue by replacing the contents of `report.xml` in your repo with my coverage file and running the test `parse kover report from xml file`. I wasn't expecting the test to pass of course, but I thought it might produce the same exception and I could catch it in the debugger. Unfortunately, parsing succeeded!

Do you have any other ideas on how I could debug this on my end?

**Comment by humblehacker** [comment]
It seems that whatever issue is triggering this problem is transient in the generation of `report.xml`. I thought maybe my test above didn't give me the results I was looking for because I had generated the coverage file locally, while the failure occurred on GitHub Actions. Maybe there was something about the different platform that was causing a problem with the generated file. So I updated my workflow to save the file as an artifact. However, when the workflow ran, `kover-report` did not fail!

So I guess I leave it like this for now. If I do encounter the failure again, at least I'll have access to the problematic XML file and maybe then we can find the cause.

**Comment by mi-kas** [comment]
Thanks for the insights! I will close this issue now, but feel free to come back to it if you encounter this error again

**Comment by mi-kas** [comment]
@humblehacker I just released a new beta version with a fix that I think might solve your issue. Could you try to use `mi-kas/kover-report@v1.2-beta` in your action and let me know if the error still occurs?

**Comment by humblehacker** [comment]
Thanks for the quick response! I'll give this a try and let you know. Since it's a transient issue, it'll take a few clean builds before I'll be able to give a fairly certain 👍

**Comment by mi-kas** [comment]
@humblehacker Did you encounter the issue again?

**Comment by mi-kas** [comment]
@humblehacker I will close this issue now, but feel free to come back to it if you encounter the error again in your builds.
