### ISSUE TITLE
Update usage example for PRs originating in forks

### ISSUE THREAD

**Issue by msfjarvis** [mi-kas/kover-report#87]
GitHub severely limits what access the default `GITHUB_TOKEN` for a PR originating from a fork has, which prevents the default configuration of this action from successfully posting the report as a PR comment. You can see an example failure [here](https://github.com/android-password-store/kage/actions/runs/3828769963/jobs/6514720462).

The README should be updated so that the example also works for this scenario.

**Comment by mi-kas** [comment]
Closed by 44e3c0573ccb249bc6cebae0593bcc8d054fc5d5
